// Code generated by protoc-gen-go. DO NOT EDIT.
// source: note.proto

package note

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppListReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppListReq) Reset()         { *m = AppListReq{} }
func (m *AppListReq) String() string { return proto.CompactTextString(m) }
func (*AppListReq) ProtoMessage()    {}
func (*AppListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{0}
}

func (m *AppListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListReq.Unmarshal(m, b)
}
func (m *AppListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListReq.Marshal(b, m, deterministic)
}
func (m *AppListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListReq.Merge(m, src)
}
func (m *AppListReq) XXX_Size() int {
	return xxx_messageInfo_AppListReq.Size(m)
}
func (m *AppListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppListReq proto.InternalMessageInfo

func (m *AppListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppListReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AppListResp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppListResp) Reset()         { *m = AppListResp{} }
func (m *AppListResp) String() string { return proto.CompactTextString(m) }
func (*AppListResp) ProtoMessage()    {}
func (*AppListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_640dafe07df50d4e, []int{1}
}

func (m *AppListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResp.Unmarshal(m, b)
}
func (m *AppListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResp.Marshal(b, m, deterministic)
}
func (m *AppListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResp.Merge(m, src)
}
func (m *AppListResp) XXX_Size() int {
	return xxx_messageInfo_AppListResp.Size(m)
}
func (m *AppListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResp proto.InternalMessageInfo

func (m *AppListResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AppListResp) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*AppListReq)(nil), "note.AppListReq")
	proto.RegisterType((*AppListResp)(nil), "note.AppListResp")
}

func init() { proto.RegisterFile("note.proto", fileDescriptor_640dafe07df50d4e) }

var fileDescriptor_640dafe07df50d4e = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x2f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x0c, 0xb8, 0xb8, 0x1c, 0x0b,
	0x0a, 0x7c, 0x32, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x6b, 0x2e, 0x6e, 0xb8, 0x8e, 0xe2,
	0x02, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0x22, 0x24, 0x6d, 0x70, 0xbe, 0x90, 0x00, 0x17,
	0x73, 0x62, 0x7a, 0x2a, 0x54, 0x2f, 0x88, 0x69, 0x64, 0xc9, 0xc5, 0xe2, 0x97, 0x5f, 0x92, 0x2a,
	0x64, 0xc8, 0xc5, 0xe5, 0x9e, 0x5a, 0x02, 0x35, 0x47, 0x48, 0x40, 0x0f, 0xec, 0x2e, 0x84, 0x43,
	0xa4, 0x04, 0xd1, 0x44, 0x8a, 0x0b, 0x92, 0xd8, 0xc0, 0xce, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x02, 0xce, 0xc9, 0x0b, 0xc4, 0x00, 0x00, 0x00,
}

// This following code was generated by rpcx
// Gernerated from note.proto
type Note struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *Note) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *Note) AddServant(imp impNote, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *Note) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

type impNote interface {
	GetAppList(input AppListReq) (output AppListResp, err error)
}

// GetAppList is client rpc method as defined
func (obj *Note) GetAppList(input AppListReq) (output AppListResp, err error) {
	var _status map[string]string
	var _context map[string]string
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}
	resp := new(requestf.ResponsePacket)
	ctx := context.Background()
	err = obj.s.Tars_invoke(ctx, 0, "GetAppList", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}
	return output, nil
}
